# -*- coding: utf-8 -*-
"""NER_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192ZJ8VQql3CrnVSwUDljtkPoW0U405oY
"""

!pip install transformers seqeval[gpu]

!pip install unidecode

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import torch
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from transformers import BertForTokenClassification, BertTokenizerFast, BertConfig, BertModel

from torch import cuda
device = 'cuda' if cuda.is_available() else 'cpu'
print(device)

data = pd.read_csv("./train.csv", encoding='unicode_escape',nrows=1500000)
data.head()

d = pd.DataFrame(data.LABEL.value_counts())
d = d.loc[d.LABEL >= 145]
d = list(d.index)
len(d)

data = data.loc[data['LABEL'].isin(d)]

data.shape

f = open("data.csv", "w")
f.write('sentence_id,word,label\n')

import re
def remove_special_characters(word):
  # w=re.split("[\\,;&|+%$!~.:/%^#\-@?\'\"(){}\[\]]",word)
  w=re.sub("[\W+\_]", "",word,0,re.IGNORECASE)
  new_word="".join(w)
  return new_word

def remove_accents(word):
  new_word= unidecode.unidecode(word)
  return new_word

import re
import unidecode
index = 0
tag = 'O'
for A_ID,text,location,label in np.array(data):
  Words = text.split()
  word_index = 0
  for word in Words:
    word=remove_special_characters(word)
    word=remove_accents(word)
    if word_index == location:
      f.write(f'Sentence:{index},{word},{label}\n')
    else:
      f.write(f'Sentence:{index},{word},{tag}\n')
    word_index += 1
    f.write('\n')
  index += 1

f.close()

data2 = pd.read_csv('data.csv')

data2.count()

print("Number of unique labels: {}".format(len(data2.label.unique())))
frequencies = data2.label.value_counts()
frequencies

labels = {}
for label, count in zip(frequencies.index, frequencies):
    if label != "O":
        if label not in labels.keys():
            labels[label] = count
        else:
            labels[label] += count
    continue

print(sorted(labels.items(), key=lambda x: x[1], reverse=True))

labels_to_ids = {k: v for v, k in enumerate(data2.label.unique())}
ids_to_labels = {v: k for v, k in enumerate(data2.label.unique())}
labels_to_ids

data2

labels = list(data2.label.unique())

# let's create a new column called "sentence" which groups the words by sentence
data2['sentence'] = data2[['sentence_id','word','label']].groupby(['sentence_id'])['word'].transform(lambda x: ' '.join(map(str, x)))
# let's also create a new column called "word_labels" which groups the tags by sentence
data2['word_labels'] = data2[['sentence_id','word','label']].groupby(['sentence_id'])['label'].transform(lambda x: ','.join(map(str,x)))
data2.head()

data2 = data2[["sentence", "word_labels"]].drop_duplicates().reset_index(drop=True)
data2.head()

len(data2)

data2.iloc[41].sentence

data2.iloc[41].word_labels

MAX_LEN = 320
TRAIN_BATCH_SIZE = 2
VALID_BATCH_SIZE = 1
EPOCHS = 4
MAX_GRAD_NORM = 10
LEARNING_RATE = 1e-05
tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')

class dataset(Dataset):
  def __init__(self, dataframe,labels, tokenizer, max_len):
        self.len = len(dataframe)
        self.data = dataframe
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

  def __getitem__(self, index):
        # step 1: get the sentence and word labels
        sentence = self.data.sentence[index].strip()
        word_labels = self.data.word_labels[index].split(",")

        # step 2: use tokenizer to encode sentence (includes padding/truncation up to max length)
        # BertTokenizerFast provides a handy "return_offsets_mapping" functionality for individual tokens
        encoding = self.tokenizer(sentence,
#                              is_split_into_words=True,
                             add_special_tokens=True,
                             return_offsets_mapping=True,
                             max_length=self.max_len,
                             padding='max_length',
                             truncation=True
                             )

        # step 3: create token labels only for first word pieces of each tokenized word
        labels = [labels_to_ids[label] for label in word_labels]
        # code based on https://huggingface.co/transformers/custom_datasets.html#tok-ner
        # create an empty array of -100 of length max_length
        encoded_labels = np.ones(len(encoding["offset_mapping"]), dtype=int) * -100
        # set only labels whose first offset position is 0 and the second is not 0
        i = 0
        for idx, mapping in enumerate(encoding["offset_mapping"]):
          if mapping[0] == 0 and mapping[1] != 0:
            # overwrite label
            encoded_labels[idx] = labels[i]
            i += 1

        # step 4: turn everything into PyTorch tensors
        item = {key: torch.as_tensor(val) for key, val in encoding.items()}
        item['labels'] = torch.as_tensor(encoded_labels)

        return item

  def __len__(self):
        return self.len

train_size = 0.75
train_dataset = data2.sample(frac=train_size,random_state=105)
test_dataset = data2.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)

print("FULL Dataset: {}".format(data2.shape))
print("TRAIN Dataset: {}".format(train_dataset.shape))
print("TEST Dataset: {}".format(test_dataset.shape))

training_set = dataset(train_dataset,labels, tokenizer, MAX_LEN)
testing_set = dataset(test_dataset,labels, tokenizer, MAX_LEN)

data2.drop(data2.index)

train_params = {'batch_size': TRAIN_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

test_params = {'batch_size': VALID_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

training_loader = DataLoader(training_set, **train_params)
testing_loader = DataLoader(testing_set, **test_params)

model = BertForTokenClassification.from_pretrained('bert-base-cased', num_labels=len(labels_to_ids))
model.to(device)

optimizer = torch.optim.Adam(params=model.parameters(), lr=LEARNING_RATE)

# Defining the training function on the 80% of the dataset for tuning the bert model
def train(epoch):
    tr_loss, tr_accuracy = 0, 0
    nb_tr_examples, nb_tr_steps = 0, 0
    tr_preds, tr_labels = [], []
    # put model in training mode
    model.train()

    for idx, batch in enumerate(training_loader):

        ids = batch['input_ids'].to(device, dtype = torch.long)
        mask = batch['attention_mask'].to(device, dtype = torch.long)
        labels = batch['labels'].to(device, dtype = torch.long)

        outputs = model(input_ids=ids, attention_mask=mask, labels=labels)
        loss = outputs["loss"]
        tr_logits = outputs["logits"]
        tr_loss += loss.item()

        nb_tr_steps += 1
        nb_tr_examples += labels.size(0)

        # print(idx)
        if idx % 100==0:
            loss_step = tr_loss/nb_tr_steps
            print(f"Training loss per 100 training steps: {loss_step}")

        # compute training accuracy
        flattened_targets = labels.view(-1) # shape (batch_size * seq_len,)
        active_logits = tr_logits.view(-1, model.num_labels) # shape (batch_size * seq_len, num_labels)
        flattened_predictions = torch.argmax(active_logits, axis=1) # shape (batch_size * seq_len,)

        # only compute accuracy at active labels
        active_accuracy = labels.view(-1) != -100 # shape (batch_size, seq_len)
#         active_labels = torch.where(active_accuracy, labels.view(-1), torch.tensor(-100).type_as(labels))

        labels = torch.masked_select(flattened_targets, active_accuracy)
        predictions = torch.masked_select(flattened_predictions, active_accuracy)

        tr_labels.extend(labels)
        tr_preds.extend(predictions)

        tmp_tr_accuracy = accuracy_score(labels.cpu().numpy(), predictions.cpu().numpy())
        tr_accuracy += tmp_tr_accuracy

        # gradient clipping
        torch.nn.utils.clip_grad_norm_(
            parameters=model.parameters(), max_norm=MAX_GRAD_NORM
        )

        # backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    epoch_loss = tr_loss / nb_tr_steps
    tr_accuracy = tr_accuracy / nb_tr_steps
    print(f"Training loss epoch: {epoch_loss}")
    print(f"Training accuracy epoch: {tr_accuracy}")

for epoch in range(EPOCHS):
    print(f"------------------------------------{epoch}-----------------------------------")
    train(epoch)

def valid(model, testing_loader):
    # put model in evaluation mode
    model.eval()

    eval_loss, eval_accuracy = 0, 0
    nb_eval_examples, nb_eval_steps = 0, 0
    eval_preds, eval_labels = [], []

    with torch.no_grad():
        for idx, batch in enumerate(testing_loader):
          ids = batch['input_ids'].to(device, dtype = torch.long)
          mask = batch['attention_mask'].to(device, dtype = torch.long)
          labels = batch['labels'].to(device, dtype = torch.long)

          outputs = model(input_ids=ids, attention_mask=mask, labels=labels)
          loss = outputs["loss"]
          eval_logits = outputs["logits"]
          eval_loss += loss.item()


          nb_eval_steps += 1
          nb_eval_examples += labels.size(0)

          if idx % 100==0:
              loss_step = eval_loss/nb_eval_steps
              print(f"Validation loss per 100 evaluation steps: {loss_step}")

          # compute evaluation accuracy
          flattened_targets = labels.view(-1) # shape (batch_size * seq_len,)
          active_logits = eval_logits.view(-1, model.num_labels) # shape (batch_size * seq_len, num_labels)
          flattened_predictions = torch.argmax(active_logits, axis=1) # shape (batch_size * seq_len,)

          # only compute accuracy at active labels
          active_accuracy = labels.view(-1) != -100 # shape (batch_size, seq_len)

          labels = torch.masked_select(flattened_targets, active_accuracy)
          predictions = torch.masked_select(flattened_predictions, active_accuracy)

          eval_labels.extend(labels)
          eval_preds.extend(predictions)

          tmp_eval_accuracy = accuracy_score(labels.cpu().numpy(), predictions.cpu().numpy())
          eval_accuracy += tmp_eval_accuracy

    labels = [[ids_to_labels[id.item()] for id in eval_labels]]
    predictions = [[ids_to_labels[id.item()] for id in eval_preds]]

    eval_loss = eval_loss / nb_eval_steps
    eval_accuracy = eval_accuracy / nb_eval_steps
    print(f"Validation Loss: {eval_loss}")
    print(f"Validation Accuracy: {eval_accuracy}")

    return labels, predictions

labels, predictions = valid(model, testing_loader)

from seqeval.metrics import classification_report,f1_score

print(classification_report(labels, predictions))

import os

directory = "./model_2"

if not os.path.exists(directory):
    os.makedirs(directory)

# save vocabulary of the tokenizer
tokenizer.save_vocabulary(directory)
# save the model weights and its configuration file
model.save_pretrained(directory)
print('All files saved')

